# Generated by Django 6.0.3 on 2026-04-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('pos', '0005_alter_cashregister_opened_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='pos_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_log', to='pos.payment'),
        ),
    ]
