# Generated by Django 6.0.6 on 2026-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_maintenancelog_pos_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text="Laisser vide si cette machine n'a pas d'entretien periodique.", null=True, verbose_name='Intervalle de maintenance (jours)'),
        ),
    ]
