# Generated by Django 6.0.6 on 2026-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_maintenance_interval_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='declassed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Declasse le'),
        ),
        migrations.AddField(
            model_name='machine',
            name='declassed_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motif du declassement'),
        ),
        migrations.AddField(
            model_name='machine',
            name='equipment_type',
            field=models.CharField(choices=[('machine', 'Machine'), ('accessory', 'Accessoire')], db_index=True, default='machine', max_length=20, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text="Laisser vide si cet equipement n'a pas d'entretien periodique.", null=True, verbose_name='Intervalle de maintenance (jours)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('maintenance', 'Maintenance'), ('broken', 'En panne'), ('declasse', 'Declasse')], default='ok', max_length=20),
        ),
    ]
