# Generated by Django 5.1.6 on 2026-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cashregister_closed_by_cashregister_closing_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='session_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
