# Generated by Django 5.1.6 on 2026-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cashregister_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='session_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
