# Generated by Django 5.1.6 on 2026-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cashregister_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], default='in', max_length=10),
        ),
    ]
