# Generated by Django 5.1.6 on 2026-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payment_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
