# Generated by Django 5.1.6 on 2026-03-09 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cashregister_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
