# Generated by Django 5.1.6 on 2026-03-09 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_qr_code_member_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
