# Generated by Django 5.1.6 on 2026-03-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_member_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date']},
        ),
    ]
