# Generated by Django 5.1.6 on 2026-03-18 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_options'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['organization'], name='core_gym_organiz_343747_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym'], name='core_member_gym_id_2089e1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'status'], name='core_member_gym_id_d0961d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'created_at'], name='core_member_gym_id_4a2bce_idx'),
        ),
    ]
