# Generated by Django 6.0.3 on 2026-04-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_payment_category_payment_created_by_and_more'),
        ('rh', '0002_alter_attendance_options_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='pos_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_record', to='pos.payment'),
        ),
    ]
