# Generated by Django 6.0.3 on 2026-05-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        ('rh', '0003_paymentrecord_pos_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='compensation_type',
            field=models.CharField(choices=[('daily', 'Salaire journalier'), ('monthly', 'Salaire mensuel fixe')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Especes'), ('bank_transfer', 'Virement bancaire'), ('check', 'Cheque')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='reference',
            field=models.CharField(blank=True, help_text='Numero de recu/virement', max_length=100),
        ),
        migrations.CreateModel(
            name='PayrollSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Approuve'), ('paid', 'Paye')], default='draft', max_length=20)),
                ('compensation_type', models.CharField(choices=[('daily', 'Salaire journalier'), ('monthly', 'Salaire mensuel fixe')], max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('present_days', models.IntegerField(default=0)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_slips', to='rh.employee')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_slips', to='organizations.gym')),
                ('payment_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_slip', to='rh.paymentrecord')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee__name'],
                'indexes': [models.Index(fields=['gym', 'year', 'month'], name='rh_payrolls_gym_id_8405ad_idx'), models.Index(fields=['gym', 'status'], name='rh_payrolls_gym_id_41a391_idx')],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
