# Generated by Django 6.0.3 on 2026-05-22 14:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        ('rh', '0004_employee_compensation_type_employee_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollslip',
            name='advance_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='bonus_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='deduction_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='leave_deduction_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='overtime_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='paid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='unpaid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('paid', 'Conge paye'), ('unpaid', 'Conge sans solde'), ('sick', 'Conge maladie')], default='paid', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='rh.employee')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='organizations.gym')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['gym', 'status'], name='rh_leavereq_gym_id_b27c8f_idx'), models.Index(fields=['employee', 'start_date'], name='rh_leavereq_employe_ea7ffd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_entries', to='rh.employee')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_entries', to='organizations.gym')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['gym', 'status'], name='rh_overtime_gym_id_8a6bc0_idx'), models.Index(fields=['employee', 'work_date'], name='rh_overtime_employe_80d524_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Prime'), ('advance', 'Avance'), ('deduction', 'Retenue')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='rh.employee')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='organizations.gym')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['gym', 'year', 'month'], name='rh_payrolla_gym_id_6d460c_idx'), models.Index(fields=['employee', 'year', 'month'], name='rh_payrolla_employe_a86038_idx')],
            },
        ),
    ]
