# Generated by Django 6.0.3 on 2026-05-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_payrollslip_advance_total_payrollslip_bonus_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollslip',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_slips_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_slips_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('reviewed', 'Verifie'), ('approved', 'Approuve'), ('paid', 'Paye')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('review', 'Verification'), ('approve', 'Approbation'), ('pay', 'Paiement')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='rh.payrollslip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
