# Generated by Django 6.0.3 on 2026-05-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        ('rh', '0006_payrollslip_approved_by_payrollslip_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollslip',
            name='employee_contribution_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='employee_tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='employer_contribution_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PayrollContributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('party', models.CharField(choices=[('employee_tax', 'Taxe employee'), ('employee_contribution', 'Cotisation employee'), ('employer_contribution', 'Cotisation employeur')], max_length=30)),
                ('calculation_type', models.CharField(choices=[('percentage', 'Pourcentage du brut'), ('fixed', 'Montant fixe')], default='percentage', max_length=20)),
                ('rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_contribution_rules', to='organizations.gym')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['gym', 'is_active'], name='rh_payrollc_gym_id_dfc772_idx')],
            },
        ),
    ]
