# Generated by Django 6.0.6 on 2026-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('manuelle', 'Saisie a la main'), ('lecteur', 'Passage au lecteur')], default='manuelle', max_length=10),
        ),
    ]
