# Generated by Django 6.0.6 on 2026-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_presence_par_le_lecteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
