# Generated by Django 6.0.6 on 2026-09-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_heure_de_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('coach', 'Coach'), ('reception', 'Accueil'), ('cashier', 'Caissier'), ('commercial', 'Commercial'), ('cleaner', "Agent d'entretien")], max_length=50),
        ),
    ]
