# Generated by Django 6.0.6 on 2026-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietaire'), ('manager', 'Manager'), ('coach', 'Coach'), ('reception', 'Accueil'), ('cashier', 'Caissier'), ('commercial', 'Commercial'), ('cleaner', "Agent d'entretien")], max_length=50),
        ),
    ]
