# Generated by Django 5.1.6 on 2026-03-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_048085_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GymModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='organizations.gym')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_modules', to='organizations.module')),
            ],
            options={
                'indexes': [models.Index(fields=['gym'], name='organizatio_gym_id_7e36ee_idx'), models.Index(fields=['gym', 'is_active'], name='organizatio_gym_id_8912d2_idx')],
                'unique_together': {('gym', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['organization'], name='organizatio_organiz_2b20e1_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['subdomain'], name='organizatio_subdoma_deb2da_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['organization', 'created_at'], name='organizatio_organiz_5b728e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gym',
            unique_together={('organization', 'slug')},
        ),
    ]
