# Generated by Django 6.0.6 on 2026-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_subscription_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='maintenance_alert_lead_days',
            field=models.PositiveIntegerField(default=14, help_text="Nombre de jours avant l'echeance ou l'alerte apparait.", verbose_name='Prevenance maintenance (jours)'),
        ),
    ]
