# Generated by Django 6.0.6 on 2026-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_gym_maintenance_alert_lead_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse de la salle'),
        ),
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail de la salle'),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_hours',
            field=models.TextField(blank=True, default='', help_text='Texte libre, une ligne par plage. Ex : Lundi au vendredi 06h - 21h', verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telephone de la salle'),
        ),
    ]
