# Generated by Django 6.0.6 on 2026-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_gym_address_gym_email_gym_opening_hours_gym_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Page Facebook'),
        ),
        migrations.AddField(
            model_name='organization',
            name='footer_services',
            field=models.TextField(blank=True, default='', help_text='Un service par ligne. Ex : Musculation', verbose_name='Services listes en pied de page'),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Compte Instagram'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', verbose_name='Compte TikTok'),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Indicatif et numero, sans + ni espaces. Ex : 243810000000', max_length=20, verbose_name='Numero WhatsApp'),
        ),
    ]
