# Generated by Django 6.0.6 on 2026-08-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='opening_hours',
            field=models.TextField(blank=True, default='', help_text='Texte libre. Ex : Lundi au samedi, 06h - 21h', verbose_name='Horaires affiches sur le site public'),
        ),
    ]
