# Generated by Django 6.0.6 on 2026-08-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Reprise dans les accroches et la fiche etablissement.', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/landing/', verbose_name='Photo principale'),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/landing/', verbose_name='Photo espace 1'),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/landing/', verbose_name='Photo espace 2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/landing/', verbose_name='Photo espace 3'),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_intro',
            field=models.TextField(blank=True, default='', help_text='Le paragraphe sous le titre principal.', verbose_name="Phrase d'introduction"),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_kicker',
            field=models.CharField(blank=True, default='', help_text='Ex : Salle de sport premium a Kinshasa', max_length=160, verbose_name='Petite accroche au-dessus du titre'),
        ),
        migrations.AddField(
            model_name='organization',
            name='landing_title',
            field=models.CharField(blank=True, default='', help_text='Affiche sous le nom. Ex : Entrainez-vous comme un roi', max_length=160, verbose_name='Titre principal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='seo_description',
            field=models.TextField(blank=True, default='', help_text="Environ 160 caracteres. Reprise aussi lors d'un partage sur les reseaux.", verbose_name='Description pour les moteurs de recherche'),
        ),
        migrations.AddField(
            model_name='organization',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', help_text='Separes par des virgules.', max_length=255, verbose_name='Mots-cles'),
        ),
        migrations.CreateModel(
            name='LandingFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Decochee, la question reste enregistree mais disparait du site.', verbose_name='Affichee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_faqs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Question frequente',
                'verbose_name_plural': 'Questions frequentes',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_f61dd5_idx')],
            },
        ),
    ]
