# Generated by Django 6.0.6 on 2026-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_city_organization_landing_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_public_prices',
            field=models.BooleanField(default=False, help_text='Decochee, la page affiche les formules et leur contenu sans montant, et invite le prospect a contacter la salle.', verbose_name='Afficher les prix sur le site public'),
        ),
    ]
