# Generated by Django 5.1.6 on 2026-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
        ('members', '0002_remove_member_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='members.member'),
        ),
    ]
