# Generated by Django 6.0.3 on 2026-05-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0008_coachassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coachassignment',
            new_name='coaching_co_gym_id_064652_idx',
            old_name='coaching_as_gym_id_31119e_idx',
        ),
        migrations.RenameIndex(
            model_name='coachassignment',
            new_name='coaching_co_coach_i_848ee6_idx',
            old_name='coaching_as_coach_i_45df6e_idx',
        ),
        migrations.RenameIndex(
            model_name='coachassignment',
            new_name='coaching_co_member__e66784_idx',
            old_name='coaching_as_member__3e1b94_idx',
        ),
        migrations.RenameIndex(
            model_name='coachassignment',
            new_name='coaching_co_gym_id_f53993_idx',
            old_name='coaching_as_gym_id_f70cf0_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfeedback',
            new_name='coaching_co_gym_id_5b176d_idx',
            old_name='coaching_fe_gym_id_2b6f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfeedback',
            new_name='coaching_co_coach_i_13ae27_idx',
            old_name='coaching_fe_coach_i_ba5dc7_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfeedback',
            new_name='coaching_co_member__fbe3b9_idx',
            old_name='coaching_fe_member__ebc133_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfollowup',
            new_name='coaching_co_gym_id_6e9414_idx',
            old_name='coaching_fo_gym_id_f0a179_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfollowup',
            new_name='coaching_co_coach_i_038474_idx',
            old_name='coaching_fo_coach_i_c21878_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfollowup',
            new_name='coaching_co_member__51da42_idx',
            old_name='coaching_fo_member__7ba92f_idx',
        ),
        migrations.RenameIndex(
            model_name='coachingfollowup',
            new_name='coaching_co_gym_id_e6e6cf_idx',
            old_name='coaching_fo_gym_id_f5a329_idx',
        ),
        migrations.RenameIndex(
            model_name='groupcoachingprogram',
            new_name='coaching_gr_gym_id_3700b2_idx',
            old_name='coaching_gr_gym_id_9e4c79_idx',
        ),
    ]
