# Generated by Django 5.1.6 on 2026-03-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.membersubscription'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['gym'], name='pos_cashreg_gym_id_ea93a7_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['gym', 'is_closed'], name='pos_cashreg_gym_id_629f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['gym', 'date'], name='pos_exchang_gym_id_69c2f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('gym', 'date')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym'], name='pos_payment_gym_id_8aca55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='pos_payment_status_19c24f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'status'], name='pos_payment_gym_id_340b93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'created_at'], name='pos_payment_gym_id_2909d5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['type'], name='pos_payment_type_769936_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['currency'], name='pos_payment_currenc_73fd6d_idx'),
        ),
    ]
