# Generated by Django 6.0.3 on 2026-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux fige pour cette session: 1 USD = X CDF', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de reference en USD lorsque la vente est pricee en USD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_cdf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
