# Generated by Django 6.0.3 on 2026-04-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_active'),
        ('organizations', '0003_organization_logo'),
        ('pos', '0005_alter_cashregister_opened_by'),
        ('products', '0002_alter_stockmovement_options'),
        ('subscriptions', '0003_alter_subscriptionplan_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('subscription', 'Abonnement'), ('product', 'Vente produit'), ('salary', 'Salaire'), ('maintenance', 'Maintenance'), ('expense', 'Depense'), ('other', 'Autre')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_app',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Cheque')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'category'], name='pos_payment_gym_id_26438e_idx'),
        ),
    ]
