# Generated by Django 6.0.3 on 2026-06-13 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_subscription_pack'),
        ('pos', '0006_payment_category_payment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed', False)), fields=('gym', 'opened_by'), name='unique_open_register_per_user_and_gym'),
        ),
    ]
