# Generated by Django 6.0.6 on 2026-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_cashregister_unique_open_register_per_user_and_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Especes'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Cheque')], max_length=20),
        ),
    ]
