# Generated by Django 6.0.6 on 2026-09-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_registers', to=settings.AUTH_USER_MODEL, verbose_name='Cloture validee par'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='validation_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
