# Generated by Django 6.0.6 on 2026-09-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_cashregister_validated_at_cashregister_validated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='pos.payment', verbose_name='Retour sur ce decaissement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('subscription', 'Abonnement'), ('product', 'Vente produit'), ('salary', 'Salaire'), ('maintenance', 'Maintenance'), ('expense', 'Depense'), ('expense_refund', 'Retour de decaissement'), ('cash_injection', 'Apport en caisse'), ('other', 'Autre')], db_index=True, default='other', max_length=30),
        ),
    ]
