# Generated by Django 6.0.6 on 2026-09-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_payment_refund_of_alter_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='beneficiaire',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='motif_offert',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='offert',
            field=models.BooleanField(default=False, verbose_name='Offert'),
        ),
        migrations.AddField(
            model_name='payment',
            name='valeur_offerte_cdf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur offerte (CDF)'),
        ),
    ]
