# Generated by Django 6.0.6 on 2026-09-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_annulation_geste_offert'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vente_corrigee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='pos.payment', verbose_name='Correction de cette vente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('subscription', 'Abonnement'), ('product', 'Vente produit'), ('salary', 'Salaire'), ('maintenance', 'Maintenance'), ('expense', 'Depense'), ('expense_refund', 'Retour de decaissement'), ('cash_injection', 'Apport en caisse'), ('sale_correction', 'Correction de vente'), ('other', 'Autre')], db_index=True, default='other', max_length=30),
        ),
    ]
