# Generated by Django 6.0.6 on 2026-09-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_payment_vente_corrigee_alter_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='caisse_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_repris_par', to='pos.cashregister', verbose_name='Caisse dont le fonds est repris'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='provenance_fonds',
            field=models.CharField(choices=[('reprise', 'Repris de la caisse precedente'), ('apport', "Apporte de l'exterieur"), ('inconnue', 'Non precisee')], default='inconnue', max_length=20, verbose_name="Provenance du fonds d'ouverture"),
        ),
    ]
