# Generated by Django 5.1.6 on 2026-04-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersubscription',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Abonnement en pause'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en pause'),
        ),
    ]
