# Generated by Django 5.1.6 on 2026-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('subscriptions', '0002_membersubscription_is_paused_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='unique_plan_name_per_gym'),
        ),
    ]
