# Generated by Django 6.0.3 on 2026-05-24 05:39

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_legacy_coaching_rights_to_offers(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionOffer = apps.get_model("subscriptions", "SubscriptionOffer")

    for plan in SubscriptionPlan.objects.select_related("gym").all():
        offers_to_assign = []
        if plan.coaching_mode in {"individual", "both"}:
            offer, _ = SubscriptionOffer.objects.get_or_create(
                gym=plan.gym,
                name="Acces coaching individuel",
                defaults={
                    "code": slugify("Acces coaching individuel"),
                    "category": "coaching",
                    "description": "Offre migree depuis les anciens droits coaching individuels.",
                    "grants_individual_coaching": True,
                    "grants_group_coaching": False,
                    "is_active": True,
                },
            )
            offers_to_assign.append(offer)
        if plan.coaching_mode in {"group", "both"}:
            offer, _ = SubscriptionOffer.objects.get_or_create(
                gym=plan.gym,
                name="Acces coaching groupe",
                defaults={
                    "code": slugify("Acces coaching groupe"),
                    "category": "coaching",
                    "description": "Offre migree depuis les anciens droits coaching groupe.",
                    "grants_individual_coaching": False,
                    "grants_group_coaching": True,
                    "is_active": True,
                },
            )
            offers_to_assign.append(offer)

        if offers_to_assign:
            plan.offers.add(*offers_to_assign)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        ('subscriptions', '0005_subscriptionplan_coaching_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(editable=False, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('access', 'Acces'), ('coaching', 'Coaching'), ('class', 'Cours'), ('other', 'Autre')], default='access', max_length=20)),
                ('grants_individual_coaching', models.BooleanField(default=False)),
                ('grants_group_coaching', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_offers', to='organizations.gym')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='plans', to='subscriptions.subscriptionoffer'),
        ),
        migrations.AddIndex(
            model_name='subscriptionoffer',
            index=models.Index(fields=['gym', 'is_active'], name='subscriptio_gym_id_2c2748_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionoffer',
            index=models.Index(fields=['gym', 'category'], name='subscriptio_gym_id_b0f429_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionoffer',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='unique_subscription_offer_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionoffer',
            constraint=models.UniqueConstraint(fields=('gym', 'code'), name='unique_subscription_offer_code_per_gym'),
        ),
        migrations.RunPython(migrate_legacy_coaching_rights_to_offers, noop_reverse),
    ]
