# Generated by Django 6.0.6 on 2026-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionoffer_subscriptionplan_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='guest_invites_per_month',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de personnes qu'un membre peut inviter par tranche de 30 jours d'abonnement. Zero desactive les invitations.", verbose_name="Invitations par mois d'abonnement"),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='guest_sessions_per_invite',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de passages accordes a une personne invitee.', verbose_name='Seances offertes a chaque invite'),
        ),
    ]
