# Generated by Django 6.0.6 on 2026-09-04 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_show_public_prices'),
        ('subscriptions', '0007_subscriptionplan_guest_invites_per_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_start', models.DateField(verbose_name='Ancien debut')),
                ('previous_end', models.DateField(verbose_name='Ancienne fin')),
                ('new_start', models.DateField(verbose_name='Nouveau debut')),
                ('new_end', models.DateField(verbose_name='Nouvelle fin')),
                ('reason', models.CharField(help_text='Ce que le proprietaire lira dans son bandeau.', max_length=255, verbose_name='Motif')),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_corrections_seen', to=settings.AUTH_USER_MODEL)),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_corrections', to='organizations.gym')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='subscriptions.membersubscription')),
            ],
            options={
                'verbose_name': "Correction d'abonnement",
                'verbose_name_plural': "Corrections d'abonnement",
                'ordering': ['-corrected_at'],
                'indexes': [models.Index(fields=['gym', 'acknowledged_at'], name='subscriptio_gym_id_7e6d06_idx')],
            },
        ),
    ]
