# Generated by Django 6.0.6 on 2026-09-14 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_guestpass'),
        ('organizations', '0011_organization_show_public_prices'),
        ('products', '0003_product_currency'),
        ('subscriptions', '0008_subscriptioncorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('kind', models.CharField(choices=[('credit', 'Credit a la vente'), ('remise', 'Remise au comptoir'), ('annulation', "Annulation d'une remise")], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations', to='subscriptions.benefitmovement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_movements', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_movements', to='organizations.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_movements', to='members.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_movements', to='products.product')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_movements', to='subscriptions.membersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'member', 'product'], name='subscriptio_gym_id_b01b79_idx'), models.Index(fields=['gym', 'kind', 'created_at'], name='subscriptio_gym_id_62471d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptionoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'product'), name='unique_product_per_offer')],
            },
        ),
    ]
