# Generated by Django 6.0.6 on 2026-09-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_benefitmovement_offeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncorrection',
            name='new_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_vers', to='subscriptions.subscriptionplan', verbose_name='Nouvelle formule'),
        ),
        migrations.AddField(
            model_name='subscriptioncorrection',
            name='previous_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_depuis', to='subscriptions.subscriptionplan', verbose_name='Ancienne formule'),
        ),
    ]
