# Generated by Django 5.1.6 on 2026-03-24 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='members.member'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['gym'], name='access_acce_gym_id_95cde7_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['member'], name='access_acce_member__6e1b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['check_in_time'], name='access_acce_check_i_db91c0_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['member', 'check_in_time'], name='access_acce_member__c17edb_idx'),
        ),
    ]
