# Generated by Django 6.0.3 on 2026-04-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='denial_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
