# Generated by Django 6.0.6 on 2026-08-09 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_accesslog_denial_reason'),
        ('organizations', '0005_organization_subscription_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('hikvision', 'Hikvision (ISAPI)')], default='hikvision', max_length=30)),
                ('host', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.PositiveIntegerField(default=80)),
                ('use_https', models.BooleanField(default=False)),
                ('username', models.CharField(default='admin', max_length=64)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('door_number', models.PositiveSmallIntegerField(default=1)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_devices', to='organizations.gym')),
            ],
            options={
                'verbose_name': "Lecteur d'acces",
                'verbose_name_plural': "Lecteurs d'acces",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='access.accessdevice'),
        ),
        migrations.AddIndex(
            model_name='accessdevice',
            index=models.Index(fields=['gym', 'is_active'], name='access_acce_gym_id_ad9678_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessdevice',
            constraint=models.UniqueConstraint(fields=('gym', 'host'), name='unique_access_device_host_per_gym'),
        ),
    ]
