# Generated by Django 6.0.6 on 2026-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_accessdevice_accesslog_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdevice',
            name='open_on_granted',
            field=models.BooleanField(default=True, help_text="Declenche le relais de ce lecteur quand un QR code valide est reconnu par l'application.", verbose_name='Ouvrir la porte sur acces autorise'),
        ),
    ]
