# Generated by Django 6.0.6 on 2026-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_accessdevice_open_on_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='is_return',
            field=models.BooleanField(default=False, help_text='Passage suivant une entree deja accordee le meme jour.', verbose_name='Retour dans la salle'),
        ),
    ]
