# Generated by Django 6.0.6 on 2026-08-22 19:03

import access.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_accesslog_is_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdevice',
            name='tunnel_client_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Identifiant du jeton de tunnel'),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='tunnel_client_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Secret du jeton de tunnel'),
        ),
        migrations.AlterField(
            model_name='accessdevice',
            name='host',
            field=models.CharField(max_length=253, validators=[access.models.validate_device_host], verbose_name="Adresse ou nom d'hote"),
        ),
    ]
