# Generated by Django 6.0.6 on 2026-08-22 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_accessdevice_tunnel_client_id_and_more'),
        ('members', '0011_backfill_registration_authorship'),
        ('organizations', '0011_organization_show_public_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='device_event_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="Numero d'evenement du lecteur"),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['device', 'device_event_id'], name='access_acce_device__b21db3_idx'),
        ),
    ]
