# Generated by Django 6.0.6 on 2026-08-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_nettoyer_masque_adresse'),
        ('members', '0011_backfill_registration_authorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='members.member'),
        ),
    ]
