# Generated by Django 6.0.6 on 2026-08-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_accesslog_member'),
        ('members', '0012_guestpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='guest_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='members.guestpass', verbose_name='Invitation utilisee'),
        ),
    ]
