# Generated by Django 6.0.6 on 2026-09-14 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_accesslog_guest_pass'),
        ('members', '0012_guestpass'),
        ('organizations', '0011_organization_show_public_prices'),
        ('rh', '0008_employee_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='rh.employee', verbose_name='Employe'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='terminal_label',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Fiche du terminal'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['employee', 'check_in_time'], name='access_acce_employe_3d58f2_idx'),
        ),
    ]
