# Generated by Django 6.0.6 on 2026-09-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_journal_personnel_et_fiches_terminal'),
        ('organizations', '0011_organization_show_public_prices'),
        ('rh', '0008_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReaderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=20)),
                ('nom', models.CharField(blank=True, default='', max_length=255)),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
                ('retrait_demande_le', models.DateTimeField(blank=True, null=True)),
                ('derniere_tentative_le', models.DateTimeField(blank=True, null=True)),
                ('derniere_erreur', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_records', to='access.accessdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_records', to='rh.employee')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_reader_records', to='organizations.gym')),
            ],
            options={
                'indexes': [models.Index(fields=['gym', 'retrait_demande_le'], name='access_staf_gym_id_b76b26_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'employee_no'), name='fiche_personnel_unique_par_lecteur')],
            },
        ),
    ]
