# Generated by Django 6.0.6 on 2026-09-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_fiches_du_personnel_sur_les_lecteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdevice',
            name='sens',
            field=models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], default='entree', help_text='Les passages lus par ce lecteur comptent comme des entrees, ou comme des sorties.', max_length=10, verbose_name='Sens du passage'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='sens',
            field=models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], db_index=True, default='entree', max_length=10),
        ),
    ]
