# Generated by Django 5.1.6 on 2026-04-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='coach',
        ),
    ]
