# Generated by Django 6.0.3 on 2026-04-18 22:20

import django.db.models.deletion
import members.models
import uuid
from django.conf import settings
from django.db import migrations, models


def create_pre_registration_links(apps, schema_editor):
    Gym = apps.get_model('organizations', 'Gym')
    MemberPreRegistrationLink = apps.get_model('members', 'MemberPreRegistrationLink')
    for gym in Gym.objects.all():
        MemberPreRegistrationLink.objects.get_or_create(gym=gym)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_active'),
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPreRegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_pre_registration_link', to='organizations.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberPreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmee'), ('cancelled', 'Annulee')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=members.models.default_pre_registration_expiry)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_member_pre_registrations', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_pre_registrations', to='organizations.gym')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_registration', to='members.member')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_registrations', to='members.memberpreregistrationlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='memberpreregistrationlink',
            index=models.Index(fields=['gym', 'is_active'], name='members_mem_gym_id_b0421a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpreregistration',
            index=models.Index(fields=['gym', 'status'], name='members_mem_gym_id_87d7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpreregistration',
            index=models.Index(fields=['gym', 'expires_at'], name='members_mem_gym_id_0b2848_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpreregistration',
            index=models.Index(fields=['status', 'expires_at'], name='members_mem_status_b91705_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpreregistration',
            index=models.Index(fields=['gym', 'phone'], name='members_mem_gym_id_02a2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpreregistration',
            index=models.Index(fields=['gym', 'email'], name='members_mem_gym_id_67d45b_idx'),
        ),
        migrations.RunPython(create_pre_registration_links, migrations.RunPython.noop),
    ]
