# Generated by Django 6.0.3 on 2026-05-24 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberpreregistrationlink_memberpreregistration_and_more'),
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Perte de poids'), ('gain_weight', 'Prise de poids')], max_length=20)),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('measurement_starter', models.CharField(choices=[('member', 'Le membre commence les releves'), ('coach', 'Le coach commence les releves')], default='member', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('achieved', 'Atteint'), ('cancelled', 'Annule')], db_index=True, default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_goals', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_goals', to='organizations.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberWeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('member', 'Membre'), ('coach', 'Coach')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='members.membergoal')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_weight_measurements', to='organizations.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_weight_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membergoal',
            index=models.Index(fields=['gym', 'status'], name='members_mem_gym_id_9d561f_idx'),
        ),
        migrations.AddIndex(
            model_name='membergoal',
            index=models.Index(fields=['member', 'status'], name='members_mem_member__b3d661_idx'),
        ),
        migrations.AddConstraint(
            model_name='membergoal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('member',), name='unique_active_goal_per_member'),
        ),
        migrations.AddIndex(
            model_name='memberweightmeasurement',
            index=models.Index(fields=['gym', 'measured_at'], name='members_mem_gym_id_6dd2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='memberweightmeasurement',
            index=models.Index(fields=['member', 'measured_at'], name='members_mem_member__f4e2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='memberweightmeasurement',
            index=models.Index(fields=['goal', 'measured_at'], name='members_mem_goal_id_009df3_idx'),
        ),
    ]
