# Generated by Django 6.0.6 on 2026-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_qr_code_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpreregistration',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
