# Generated by Django 6.0.6 on 2026-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberpreregistration_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmee'), ('cancelled', 'Annulee'), ('expired', 'Expiree')], db_index=True, default='pending', max_length=20),
        ),
    ]
