# Generated by Django 6.0.6 on 2026-08-18 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_extend_member_qr_validity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_registered', to=settings.AUTH_USER_MODEL, verbose_name='Inscrit par'),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_source',
            field=models.CharField(choices=[('manual', 'Saisie directe'), ('pre_registration', 'Preinscription confirmee'), ('other', 'Autre / reprise de donnees')], default='other', max_length=20, verbose_name="Origine de l'inscription"),
        ),
        migrations.AddField(
            model_name='memberpreregistration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberpreregistration',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_member_pre_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
