# Generated by Django 6.0.6 on 2026-08-27 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_backfill_registration_authorship'),
        ('organizations', '0011_organization_show_public_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120, verbose_name="Nom de l'invite")),
                ('guest_phone', models.CharField(db_index=True, help_text='Sert a reperer une personne invitee trop souvent.', max_length=30, verbose_name="Telephone de l'invite")),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sessions_allowed', models.PositiveIntegerField(default=1)),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('reassigned_count', models.PositiveIntegerField(default=0, help_text='Nombre de fois que le carnet a change de destinataire.', verbose_name='Reattributions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_passes_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_passes', to='organizations.gym')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_passes', to='members.member', verbose_name='Membre qui invite')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', '-created_at'], name='members_gue_gym_id_5760f7_idx'), models.Index(fields=['host', '-created_at'], name='members_gue_host_id_e65462_idx')],
            },
        ),
    ]
