# Generated by Django 5.1.6 on 2026-04-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('organizations', '0002_add_all_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owned_organization',
            field=models.ForeignKey(blank=True, help_text="Si l'utilisateur est Owner d'une organisation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='organizations.organization'),
        ),
    ]
