# Generated by Django 5.1.6 on 2026-03-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_saas_admin',
            field=models.BooleanField(default=False, help_text='Administrateur global du SaaS'),
        ),
        migrations.CreateModel(
            name='UserGymRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('manager', 'Manager'), ('coach', 'Coach'), ('receptionist', 'Agent Accueil'), ('accountant', 'Comptable')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['gym'], name='compte_user_gym_id_0ea121_idx')],
                'unique_together': {('user', 'gym', 'role')},
            },
        ),
    ]
