# Generated by Django 6.0.6 on 2026-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_user_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergymrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('coach', 'Coach'), ('reception', 'Receptionist'), ('cashier', 'Cashier'), ('commercial', 'Commercial')], max_length=20),
        ),
    ]
