# Generated by Django 6.0.3 on 2026-04-28 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberpreregistrationlink_memberpreregistration_and_more'),
        ('notifications', '0001_initial'),
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['gym', 'member', 'read_at'], name='notificatio_gym_id_35bada_idx'),
        ),
    ]
