# Generated by Django 6.0.6 on 2026-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD (Dollar americain)'), ('CDF', 'CDF (Franc congolais)')], default='USD', max_length=3),
        ),
    ]
